# Generated by Django 3.2.9 on 2021-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_financialtracker_tracker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackeritem',
            name='pay_amt',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
