# Generated by Django 3.2.10 on 2021-12-12 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_trackeritem_pay_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeritem',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
